LambdaForums/Controllers/ForumController.cs
using System;
using System.Linq;
using LambdaForums.Data.Models;
using LambdaForums.Service;
using LambdaForums.ViewModels.ForumViewModels;
using LambdaForums.ViewModels.PostViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LambdaForums.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForumService _forumService;
        private readonly IPostService _postService;

        public ForumController(IForumService forumService)
        {
            _forumService = forumService;
        }

        public IActionResult Index()
        {
            var forums = _forumService.GetAll()
                .Select(f => new ForumListViewModel { Id = f.Id, Description = f.Description, Title = f.Title });

            var vm = new ForumIndexViewModel
            {
                ForumList = forums
            };

            return View(vm);
        }

        public IActionResult Topic(int id)
        {
            var helper = new Helpers.ForumHelper();

            var forum = _forumService.GetById(id);
            var posts = forum.Posts;

            var postListings = posts.Select(p => new PostListingViewModel
            {
                Id = p.Id,
                AuthorId = Convert.ToInt32(p.User.Id),
                AuthorName = p.User.UserName,
                AuthorRating = p.User.Rating,
                Title = p.Title,
                DatePosted = p.Created.ToString("MMM dd yyyy"),
                RepliesCount = p.Replies.Count(),
                Forums = helper.BuildForumListing(forum)

            });

            var vm = new ForumTopicViewModel
            {
                Posts = postListings,
                Forum = helper.BuildForumListing(forum)
            };

            return View(vm);
        }
    }
}

LambdaForums/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LambdaForums.Data.Models;
using LambdaForums.Service;
using LambdaForums.ViewModels.PostViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LambdaForums.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }

        public IActionResult Index(int id)
        {
            var helper = new Helpers.PostHelper();

            var post = _postService.GetById(id);
            var replies = helper.BuildPostReplies(post.Replies);

            var vm = new PostIndexViewModel
            {
                Id = post.Id,
                Title = post.Title,
                AuthorId = post.User.Id,
                AuthorName = post.User.UserName,
                AuthorImageUrl = post.User.ProfileImageUrl,
                AuthorRating = post.User.Rating,
                Created = post.Created,
                PostContent = post.Content,
                PostReplies = replies
            };

            return View(vm);
        }
    }
}

LambdaForums/Views/Forum/Index.cshtml
@model LambdaForums.ViewModels.ForumViewModels.ForumIndexViewModel

<h1>Forums</h1>

<table class="table table-hover" id="forum-index-table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var forum in Model.ForumList)
        {
            <tr>
                <td>
                    <a asp-controller="Forum" asp-action="Topic" asp-route-id="@forum.Id">
                        @forum.Title
                    </a> 
                </td>
                <td>@forum.Description</td>
            </tr>
        }
    </tbody>
</table>

LambdaForums/Views/Forum/Topic.cshtml
@model LambdaForums.ViewModels.ForumViewModels.ForumTopicViewModel

<h1>Welcome to the @Model.Forum.Title Forum</h1>

@if (Model.Posts.Any())
{
    <table class="table table-bordered table-hover">
        <tbody>
            @foreach (var post in Model.Posts)
            {
                <tr>
                    <td>
                        <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">
                            @post.Title
                        </a>
                    </td>
                    <td>
                        @post.AuthorName
                    </td>
                    <td>
                        @post.DatePosted
                    </td>
                    <td>
                        @post.RepliesCount
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="no-posts">
        <h3>It looks like there are no @Model.Forum.Title posts yet.</h3>
        <h3>Why not 
            <a asp-controller="Post" asp-action="Create" asp-route-id="@Model.Forum.Id">Create</a>
            one?
        </h3>
    </div>
}